= flatten(imgs[0][1])
    # print(flat_img.shape)
    # plt.imshow(flat_img, cmap='Greys')
    # plt.show()
    # flat_img = resize(flat_img)
    # plt.imshow(flat_img, cmap='Greys')
    # plt.show()